
# configuration
CONFIG_FILE = 'config.json'

# usage collection
XFINITY_USER = 'XFINITY_USER'
XFINITY_PASS = 'XFINITY_PASS'
XFINITY_OFFSET = 'XFINITY_OFFSET'
XFINITY_BROWSER = 'XFINITY_BROWSER'

# usage json
JSON_USAGE = 'used'
JSON_CAP = 'total'
JSON_NOW = 'data_timestamp'

# mail warning configuration
XFINITY_WARNING = 'XFINITY_WARNING'
XFINITY_SMTP_HOST = 'XFINITY_SMTP_HOST'
XFINITY_SMTP_PORT = 'XFINITY_SMTP_PORT'
XFINITY_SMTP_USER = 'XFINITY_SMTP_USER'
XFINITY_SMTP_PASS = 'XFINITY_SMTP_PASS'
XFINITY_EMAIL_FROM = 'XFINITY_EMAIL_FROM'
XFINITY_EMAIL_TO = 'XFINITY_EMAIL_TO'
SMTP_GMAIL = 'smtp.gmail.com'
SMTP_PORT = 25
SMTP_PORT_SSL = 465
SMTP_PORT_TLS = 587

# google sheet access
XFINITY_GSHEET = 'XFINITY_GSHEET'
GSHEET_SECRET = 'client_secret.json'

# google sheet structure
DATA_SHEET_INDEX = 0
CAP_CELL = 'B2'
NOW_CELL = 'B5'
TARGET_CELL = 'B6'
USAGE_CELL = 'B7'
HIST_SHEET_INDEX = 1
HIST_MONTH_CELL = 'B1'
HIST_START_ROW = 4
HIST_START_COL = 2

# graph stuff
TMPL_FILE = 'tmpl/graph.tmpl'
GRAPH_WARNING = 0.9
